# **Testing API**

API URL to use https://west.albion-online-data.com

Endpoint
price in json
https://west.albion-online-data.com/api/v2/stats/prices/T4_HIDE.json?locations=Lymhurst,Martlock,Bridgewatch,thetford,FortSterling,Caerleon

### **Analise Combinatoria**

In [ ]:
import json
import requests
import pandas as pd
import re
from IPython.display import display
from albion_market_data_API import get_albion_prices
from albion_refine_explorer import get_refined_data
from mapping_generator import generate_tiers


with open("albion_mapping.json", "r", encoding="utf-8") as f:
    mapping = json.load(f)

item_raw = generate_tiers("HIDE")
item_raw2 = generate_tiers("LEATHER")
item_refined = generate_tiers("LEATHER")
cities = mapping["royal_cities"]

df_result = get_refined_data(item_raw, item_raw2, item_refined, cities, max_tier=6)
# df_result = df_result[
#     ["resource_end", "fee","city_raw1", "city_raw2", "city_sold", "pelego_amount", "pelego_raw", 
#      "couro_amount", "couro_raw", "couro_raw_instant", "couro_raw_order", "consumo_efetivo", "profit_instant", 
#      "profit_order", "profit_percentage_instant", "profit_percentage_order", "best_profit_percentage", "time_pelego",
#      "time_couro_raw", "time_couro_raw_instant", "time_couro_raw_order"]]

https://west.albion-online-data.com/api/v2/stats/prices/T3_HIDE,T4_HIDE,T4_HIDE_LEVEL1@1,T4_HIDE_LEVEL2@2,T4_HIDE_LEVEL3@3,T4_HIDE_LEVEL4@4,T5_HIDE,T5_HIDE_LEVEL1@1,T5_HIDE_LEVEL2@2,T5_HIDE_LEVEL3@3,T5_HIDE_LEVEL4@4,T6_HIDE,T6_HIDE_LEVEL1@1,T6_HIDE_LEVEL2@2,T6_HIDE_LEVEL3@3,T6_HIDE_LEVEL4@4,T7_HIDE,T7_HIDE_LEVEL1@1,T7_HIDE_LEVEL2@2,T7_HIDE_LEVEL3@3,T7_HIDE_LEVEL4@4,T8_HIDE,T8_HIDE_LEVEL1@1,T8_HIDE_LEVEL2@2,T8_HIDE_LEVEL3@3,T8_HIDE_LEVEL4@4,.json
https://west.albion-online-data.com/api/v2/stats/prices/T3_LEATHER,T4_LEATHER,T4_LEATHER_LEVEL1@1,T4_LEATHER_LEVEL2@2,T4_LEATHER_LEVEL3@3,T4_LEATHER_LEVEL4@4,T5_LEATHER,T5_LEATHER_LEVEL1@1,T5_LEATHER_LEVEL2@2,T5_LEATHER_LEVEL3@3,T5_LEATHER_LEVEL4@4,T6_LEATHER,T6_LEATHER_LEVEL1@1,T6_LEATHER_LEVEL2@2,T6_LEATHER_LEVEL3@3,T6_LEATHER_LEVEL4@4,T7_LEATHER,T7_LEATHER_LEVEL1@1,T7_LEATHER_LEVEL2@2,T7_LEATHER_LEVEL3@3,T7_LEATHER_LEVEL4@4,T8_LEATHER,T8_LEATHER_LEVEL1@1,T8_LEATHER_LEVEL2@2,T8_LEATHER_LEVEL3@3,T8_LEATHER_LEVEL4@4,.json
https://west.albion-online-data.com/api/v2/stats/prices/T3_LEATHER,T4_LEATHER,T4_LEATHER_LEVEL1@1,T4_LEATHER_LEVEL2@2,T4_LEATHER_LEVEL3@3,T4_LEATHER_LEVEL4@4,T5_LEATHER,T5_LEATHER_LEVEL1@1,T5_LEATHER_LEVEL2@2,T5_LEATHER_LEVEL3@3,T5_LEATHER_LEVEL4@4,T6_LEATHER,T6_LEATHER_LEVEL1@1,T6_LEATHER_LEVEL2@2,T6_LEATHER_LEVEL3@3,T6_LEATHER_LEVEL4@4,T7_LEATHER,T7_LEATHER_LEVEL1@1,T7_LEATHER_LEVEL2@2,T7_LEATHER_LEVEL3@3,T7_LEATHER_LEVEL4@4,T8_LEATHER,T8_LEATHER_LEVEL1@1,T8_LEATHER_LEVEL2@2,T8_LEATHER_LEVEL3@3,T8_LEATHER_LEVEL4@4,.json
<re.Match object; span=(0, 7), match='T3_HIDE'>
<re.Match object; span=(0, 7), match='T3_HIDE'>
<re.Match object; span=(0, 7), match='T3_HIDE'>
<re.Match object; span=(0, 7), match='T3_HIDE'>
<re.Match object; span=(0, 7), match='T3_HIDE'>
<re.Match object; span=(0, 7), match='T4_HIDE'>
<re.Match object; span=(0, 7), match='T4_HIDE'>
<re.Match object; span=(0, 7), match='T4_HIDE'>
<re.Match object; span=(0, 7), match='T4_HIDE'>
<re.Match object; span=(0, 7), match='T4_HIDE'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T4_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 7), match='T5_HIDE'>
<re.Match object; span=(0, 7), match='T5_HIDE'>
<re.Match object; span=(0, 7), match='T5_HIDE'>
<re.Match object; span=(0, 7), match='T5_HIDE'>
<re.Match object; span=(0, 7), match='T5_HIDE'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T5_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 7), match='T6_HIDE'>
<re.Match object; span=(0, 7), match='T6_HIDE'>
<re.Match object; span=(0, 7), match='T6_HIDE'>
<re.Match object; span=(0, 7), match='T6_HIDE'>
<re.Match object; span=(0, 7), match='T6_HIDE'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T6_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 7), match='T7_HIDE'>
<re.Match object; span=(0, 7), match='T7_HIDE'>
<re.Match object; span=(0, 7), match='T7_HIDE'>
<re.Match object; span=(0, 7), match='T7_HIDE'>
<re.Match object; span=(0, 7), match='T7_HIDE'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T7_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 7), match='T8_HIDE'>
<re.Match object; span=(0, 7), match='T8_HIDE'>
<re.Match object; span=(0, 7), match='T8_HIDE'>
<re.Match object; span=(0, 7), match='T8_HIDE'>
<re.Match object; span=(0, 7), match='T8_HIDE'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL1@1'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL2@2'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL3@3'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL4@4'>
<re.Match object; span=(0, 16), match='T8_HIDE_LEVEL4@4'>

In [2]:
df_result

,resource1,resource2,city_raw1,pelego_amount,pelego_raw,time_pelego,city_raw2,couro_amount,couro_raw,time_couro_raw,...,retorno,fee,consumo_efetivo,sell_tax,sell_tax_order,profit_instant,profit_order,profit_percentage_instant,profit_percentage_order,best_profit_percentage
1729,T7_HIDE_LEVEL4@4,T6_LEATHER_LEVEL4@4,Bridgewatch,2.0,0.0,None,Thetford,1.0,349935.0,03:16:35,...,0.438,0.0,196663.470,0.04,0.025,643817.490,1514281.530,327.37,769.99,769.99
1724,T7_HIDE_LEVEL4@4,T6_LEATHER_LEVEL4@4,Bridgewatch,2.0,0.0,None,Martlock,1.0,349998.0,03:16:35,...,0.438,0.0,196698.876,0.04,0.025,643782.084,1514246.124,327.29,769.83,769.83
1719,T7_HIDE_LEVEL4@4,T6_LEATHER_LEVEL4@4,Bridgewatch,2.0,0.0,None,Lymhurst,1.0,399975.0,02:36:35,...,0.438,0.0,224785.950,0.04,0.025,615695.010,1486159.050,273.90,661.14,661.14
1733,T7_HIDE_LEVEL4@4,T6_LEATHER_LEVEL4@4,Bridgewatch,2.0,0.0,None,Thetford,1.0,349935.0,03:16:35,...,0.438,0.0,196663.470,0.04,0.025,495502.290,1241370.535,251.95,631.22,631.22
1728,T7_HIDE_LEVEL4@4,T6_LEATHER_LEVEL4@4,Bridgewatch,2.0,0.0,None,Martlock,1.0,349998.0,03:16:35,...,0.438,0.0,196698.876,0.04,0.025,495466.884,1241335.129,251.89,631.08,631.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2099,T4_HIDE_LEVEL3@3,T3_LEATHER,Lymhurst,2.0,7167.0,06:11:35,Fort Sterling,1.0,224.0,07:31:35,...,0.438,134.0,8315.596,0.04,0.025,-2618.956,24.399,-31.49,0.29,0.29
2107,T4_HIDE_LEVEL3@3,T3_LEATHER,Lymhurst,2.0,7167.0,06:11:35,Martlock,1.0,226.0,02:51:35,...,0.438,134.0,8316.720,0.04,0.025,-2620.080,23.275,-31.50,0.28,0.28
2103,T4_HIDE_LEVEL3@3,T3_LEATHER,Lymhurst,2.0,7167.0,06:11:35,Lymhurst,1.0,230.0,06:11:35,...,0.438,134.0,8318.968,0.04,0.025,-2622.328,21.027,-31.52,0.25,0.25
2006,T4_HIDE_LEVEL1@1,T3_LEATHER,Bridgewatch,2.0,240.0,02:31:35,Martlock,1.0,226.0,02:51:35,...,0.438,34.0,430.772,0.04,0.025,-58.292,0.658,-13.53,0.15,0.15
2111,T4_HIDE_LEVEL3@3,T3_LEATHER,Lymhurst,2.0,7167.0,06:11:35,Thetford,1.0,264.0,02:16:35,...,0.438,134.0,8338.076,0.04,0.025,-2641.436,1.919,-31.68,0.02,0.02

In [8]:
df_result[:50]

,resource_end,fee,city_raw1,city_raw2,city_sold,pelego_amount,pelego_raw,couro_amount,couro_raw,couro_raw_instant,...,consumo_efetivo,profit_instant,profit_order,profit_percentage_instant,profit_percentage_order,best_profit_percentage,time_pelego,time_couro_raw,time_couro_raw_instant,time_couro_raw_order
19017,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Bridgewatch,2,0,1,223,875501,...,125.326,840355.634,1710819.674,670535.75,1365095.57,1365095.57,None,04:51:26,04:51:26,04:51:26
19022,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Bridgewatch,2,0,1,224,875501,...,125.888,840355.072,1710819.112,667541.84,1359000.95,1359000.95,None,07:26:26,04:51:26,04:51:26
19032,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Bridgewatch,2,0,1,226,875501,...,127.012,840353.948,1710817.988,661633.51,1346973.50,1346973.50,None,02:46:26,04:51:26,04:51:26
19027,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Bridgewatch,2,0,1,230,875501,...,129.260,840351.700,1710815.740,650125.10,1323546.14,1323546.14,None,06:06:26,04:51:26,04:51:26
19057,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Bridgewatch,2,0,1,252,875501,...,141.624,840339.336,1710803.376,593359.41,1207989.73,1207989.73,None,03:06:26,04:51:26,04:51:26
19037,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Bridgewatch,2,0,1,264,875501,...,148.368,840332.592,1710796.632,566383.99,1153076.56,1153076.56,None,02:11:26,04:51:26,04:51:26
19021,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Thetford,2,0,1,223,721006,...,125.326,692040.434,1437908.679,552192.23,1147334.69,1147334.69,None,04:51:26,14:31:26,14:31:26
19026,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Thetford,2,0,1,224,721006,...,125.888,692039.872,1437908.117,549726.64,1142212.22,1142212.22,None,07:26:26,14:31:26,14:31:26
19036,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Thetford,2,0,1,226,721006,...,127.012,692038.748,1437906.993,544860.92,1132103.26,1132103.26,None,02:46:26,14:31:26,14:31:26
19031,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Thetford,2,0,1,230,721006,...,129.260,692036.500,1437904.745,535383.34,1112412.77,1112412.77,None,06:06:26,14:31:26,14:31:26
19018,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Fort Sterling,2,0,1,223,551115,...,125.326,528945.074,1336502.929,422055.34,1066421.12,1066421.12,None,04:51:26,14:01:26,14:01:26
19023,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Fort Sterling,2,0,1,224,551115,...,125.888,528944.512,1336502.367,420170.72,1061659.86,1061659.86,None,07:26:26,14:01:26,14:01:26
19052,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Bridgewatch,2,0,1,289,875501,...,162.418,840318.542,1710782.582,517380.18,1053320.80,1053320.80,None,06:06:26,04:51:26,04:51:26
19033,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Fort Sterling,2,0,1,226,551115,...,127.012,528943.388,1336501.243,416451.51,1052263.76,1052263.76,None,02:46:26,14:01:26,14:01:26
19042,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Bridgewatch,2,0,1,290,875501,...,162.980,840317.980,1710782.020,515595.77,1049688.32,1049688.32,None,04:36:26,04:51:26,04:51:26
19062,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Bridgewatch,2,0,1,292,875501,...,164.104,840316.856,1710780.896,512063.60,1042497.99,1042497.99,None,01:56:26,04:51:26,04:51:26
19028,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Fort Sterling,2,0,1,230,551115,...,129.260,528941.140,1336498.995,409207.13,1033961.78,1033961.78,None,06:06:26,14:01:26,14:01:26
19047,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Bridgewatch,2,0,1,296,875501,...,166.352,840314.608,1710778.648,505142.47,1028408.82,1028408.82,None,06:06:26,04:51:26,04:51:26
19061,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Thetford,2,0,1,252,721006,...,141.624,692024.136,1437892.381,488634.79,1015288.64,1015288.64,None,03:06:26,14:31:26,14:31:26
19041,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Thetford,2,0,1,264,721006,...,148.368,692017.392,1437885.637,466419.57,969134.61,969134.61,None,02:11:26,14:31:26,14:31:26
19019,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Lymhurst,2,0,1,223,600021,...,125.326,575894.834,1211414.824,459517.45,966610.94,966610.94,None,04:51:26,14:41:26,14:41:26
19024,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Lymhurst,2,0,1,224,600021,...,125.888,575894.272,1211414.262,457465.58,962295.26,962295.26,None,07:26:26,14:41:26,14:41:26
19034,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Lymhurst,2,0,1,226,600021,...,127.012,575893.148,1211413.138,453416.33,953778.49,953778.49,None,02:46:26,14:41:26,14:41:26
19058,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Fort Sterling,2,0,1,252,551115,...,141.624,528928.776,1336486.631,373473.97,943686.54,943686.54,None,03:06:26,14:01:26,14:01:26
19029,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Lymhurst,2,0,1,230,600021,...,129.260,575890.900,1211410.890,445529.09,937189.30,937189.30,None,06:06:26,14:41:26,14:41:26
19038,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Fort Sterling,2,0,1,264,551115,...,148.368,528922.032,1336479.887,356493.34,900787.16,900787.16,None,02:11:26,14:01:26,14:01:26
19020,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Martlock,2,0,1,223,720001,...,125.326,691075.634,1122762.854,551422.40,895873.84,895873.84,None,04:51:26,14:36:26,14:36:26
19025,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Martlock,2,0,1,224,720001,...,125.888,691075.072,1122762.292,548960.24,891873.96,891873.96,None,07:26:26,14:36:26,14:36:26
19056,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Thetford,2,0,1,289,721006,...,162.418,692003.342,1437871.587,426063.21,885290.78,885290.78,None,06:06:26,14:31:26,14:31:26
19035,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Martlock,2,0,1,226,720001,...,127.012,691073.948,1122761.168,544101.30,883980.39,883980.39,None,02:46:26,14:36:26,14:36:26
19046,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Thetford,2,0,1,290,721006,...,162.980,692002.780,1437871.025,424593.68,882237.71,882237.71,None,04:36:26,14:31:26,14:31:26
19066,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Thetford,2,0,1,292,721006,...,164.104,692001.656,1437869.901,421684.82,876194.30,876194.30,None,01:56:26,14:31:26,14:31:26
19030,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Martlock,2,0,1,230,720001,...,129.260,691071.700,1122758.920,534636.93,868605.08,868605.08,None,06:06:26,14:36:26,14:36:26
19051,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Thetford,2,0,1,296,721006,...,166.352,691999.408,1437867.653,415985.02,864352.49,864352.49,None,06:06:26,14:31:26,14:31:26
19059,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Lymhurst,2,0,1,252,600021,...,141.624,575878.536,1211398.526,406624.96,855362.46,855362.46,None,03:06:26,14:41:26,14:41:26
19053,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Fort Sterling,2,0,1,289,551115,...,162.418,528907.982,1336465.837,325646.16,822855.74,822855.74,None,06:06:26,14:01:26,14:01:26
19043,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Fort Sterling,2,0,1,290,551115,...,162.980,528907.420,1336465.275,324522.90,820017.96,820017.96,None,04:36:26,14:01:26,14:01:26
19039,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Lymhurst,2,0,1,264,600021,...,148.368,575871.792,1211391.782,388137.46,816477.80,816477.80,None,02:11:26,14:41:26,14:41:26
19063,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Fort Sterling,2,0,1,292,551115,...,164.104,528906.296,1336464.151,322299.45,814400.72,814400.72,None,01:56:26,14:01:26,14:01:26
19048,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Fort Sterling,2,0,1,296,551115,...,166.352,528904.048,1336461.903,317942.70,803393.95,803393.95,None,06:06:26,14:01:26,14:01:26
19060,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Martlock,2,0,1,252,720001,...,141.624,691059.336,1122746.556,487953.55,792765.74,792765.74,None,03:06:26,14:36:26,14:36:26
19077,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Bridgewatch,2,0,1,400,875501,...,224.800,840256.160,1710720.200,373779.43,760996.53,760996.53,None,06:06:26,04:51:26,04:51:26
19040,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Martlock,2,0,1,264,720001,...,148.368,691052.592,1122739.812,465769.30,756726.39,756726.39,None,02:11:26,14:36:26,14:36:26
19054,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Lymhurst,Lymhurst,2,0,1,289,600021,...,162.418,575857.742,1211377.732,354552.91,745839.58,745839.58,None,06:06:26,14:41:26,14:41:26
19044,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Bridgewatch,Lymhurst,2,0,1,290,600021,...,162.980,575857.180,1211377.170,353329.97,743267.38,743267.38,None,04:36:26,14:41:26,14:41:26
19072,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Bridgewatch,2,0,1,412,875501,...,231.544,840249.416,1710713.456,362889.74,738828.67,738828.67,None,06:06:26,04:51:26,04:51:26
19064,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Lymhurst,2,0,1,292,600021,...,164.104,575856.056,1211376.046,350909.21,738175.82,738175.82,None,01:56:26,14:41:26,14:41:26
19049,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Fort Sterling,Lymhurst,2,0,1,296,600021,...,166.352,575853.808,1211373.798,346165.85,728199.12,728199.12,None,06:06:26,14:41:26,14:41:26
19087,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Thetford,Bridgewatch,2,0,1,421,875501,...,236.602,840244.358,1710708.398,355129.86,723032.10,723032.10,None,05:01:26,04:51:26,04:51:26
19082,T7_LEATHER_LEVEL4@4,0.0,Bridgewatch,Martlock,Bridgewatch,2,0,1,438,875501,...,246.156,840234.804,1710698.844,341342.40,694965.32,694965.32,None,01:11:26,04:51:26,04:51:26